class Video < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  enum :status, {
    uploading: 0,
    ready: 1,
    failed: 2
  }

  # Prefixed so the `private`/`public` values don't collide with Ruby's
  # Module#private / Module#public (methods become visibility_private?, etc.).
  enum :visibility, {
    private: 0,
    public: 1,
    unlisted: 2
  }, prefix: true

  enum :kind, {
    standalone: 0,
    feature: 1,
    episode: 2,
    trailer: 3,
    live: 4,
    tutorial: 5
  }

  belongs_to :uploader, class_name: "User", foreign_key: "uploader_id", inverse_of: :uploaded_videos

  has_many :episodes, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :subtitles, dependent: :destroy
  has_many :video_views, dependent: :destroy
  has_many :watch_progresses, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy

  # Media (Active Storage): the video file, its card thumbnail, and a short
  # (~15s) muted preview clip cut from the middle of the video. The preview is
  # generated by a separate video-processing pipeline; the home screen plays it
  # only on hover >2s and falls back to the thumbnail/poster when absent.
  has_one_attached :file
  has_one_attached :thumbnail
  has_one_attached :preview

  validates :title, :duration_seconds, presence: true
  validates :duration_seconds, numericality: { greater_than: 0 }
  validates :file_size_bytes, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

  # Most recently added first — feeds the "Recently added" rails.
  scope :recent, -> { order(created_at: :desc) }
  # Public gate for any user-facing video listing (home, sections, browse).
  scope :listable, -> { visibility_public }
  # Standalone clips for the "Recently added videos" rail (public only).
  scope :standalone_recent, -> { standalone.listable.recent }
end
